FORMAT: 1A
HOST: http://giggles.ch

# Childcare API

Childcare application API calls.

## Sign In [/api/v1.0/sign_in/{email}{password}]

#### Sign in [POST]

Performs the login (Based on the documentation here: https://github.com/timdorr/model-s-api/blob/master/apiary.apib)

Returns an `access_token` which is passed along as a header with all future requests to authenticate the user.

You must provide the `Authorization: Bearer {access_token}` header in all other requests.

+ Parameters
    + email: 'test@test.com' (string) - User email
    + password: 'pass' (string) - User password
    

+ Response 200 (application/json)
    + Body

            {
              "access_token": "abc123",
              "token_type": "bearer",
              "expires_in": 7776000
            }

## Sign out [/api/v1.0/sign_out]

#### Sign out [DELETE]

+ Request
    + Headers

            Authorization: Bearer {access_token}


+ Response 204

## My Day [/api/v1.0/my_day/{id}]

+ Parameters

    + id: `1` (number) - The id of the Child.

### Report [/api/v1.0/reports/{child_id}/{?report_date}]

Resource representing one child report.

+ Parameters
    + child_id:  4 - (number, required) - child id for the report
    + report_date:  20160226 - (string, optional) - date for the report

+ Attributes
    + id: 1 (number, required) - ID of the report
    + child_id: 4 (number, required) - ID of the child
    + user_id: 3 (number, required) - ID of the staff
    + day: 20160226 (string, required) - Day of report
    + mood: Happy (string) - Child mood
    + food: {Morning => 1 Banana, Lunch => 2 portions} (object) - Daily food
    + sleep: 11.30-12.30, 14:00 - 14:30 (array) - Sleep times
    + nappy: 3 nappies, 2 poos (array) - Nappy changes
    + milestone:  I said my first word today: Mama (string) - Mileston text
    + notes: Some notes (string) - General notes

#### List child report [GET]

Display a child report for today or in specific date

+ Request
    + Headers
    
            Authorization: Bearer {access_token}

+ Response 200 (application/json)

    + Attributes (Report)
    
#### Create a new child report [POST]

Adds a new child report.

+ Request (application/json)
    + Headers
    
            Authorization: Bearer {access_token}
    + Attributes (Report)
            
+ Response 201 (application/json)
    
    Report created.
    
    + Attributes (Report)

### Posts [/api/v1.0/child/{child_id}/posts]

Resource representing all posts for a child

+ Parameters
    + child_id: 14 - (number, required) - ID for the child
    
+ Attributes (array[Post])

#### List all posts for child [GET]

Retrieves all posts for a child

+ Parameters
    + child_id: 23 - (number, required) - ID for the child

+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)

    + Attributes (Posts)

### Post [/api/v1.0/child/{child_id}/posts/{post_id}]

Resource representing a post.

+ Parameters
    + child_id: 3 - (number, required) - ID for the child
    + post_id: 14 - (number, required) - ID for the post

+ Attributes
    + id: 34 - (number, required) - ID for the post
    + child_id: 5 - (number, required) - ID for the child
    + user_id: 33 - (number, required) - ID for the user
    + post_text: This is a post - (string, required) - Post text
    + media_url: http://test.com/resource/id - (string, optional) - URL for media
    + created_at: 20151023114534 - (string, required) - Datetime created

#### Retrieve post [GET]

Retrieves an individual post.

+ Request
    + Headers
    
            Authorization: Bearer {access_token}
            
+ Response 200 (application/json)
    + Attributes (Post)

#### Update own post [PUT]

Updates own post.

+ Request (application/json)
    + Headers
    
            Authorization: Bearer {access_token}
    
    + Attributes (Post)

+ Response 204 (application/json)

    Post updated
    
    + Attributes (Post)

#### Create a new post [POST]

Adds a new post.

+ Request (application/json)
    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (Post)
    
+ Response 201 (application/json)

    Post created.
    
    + Attributes (Post)

#### Delete my post [DELETE]

+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 204

### Comments [/api/v1.0/child/{child_id}/posts/{post_id}/comments]

Resource representing all comments for a post

+ Parameters
    + child_id: 33 - (number, required) - ID for the child
    + post_id: 12 - (number, required) - ID for the post

+ Attributes (array[Comment])

#### List all comments for a post [GET]

Retrieves all comments for a post

+ Parameters
    + child_id: 41 - (number, required) - ID for the child
    + post_id: 111 - (number, required) - ID for the post

+ Request
    + Headers
    
            Authorization: Bearer {access_token}

+ Response 200 (application/json)

    + Attributes (Comments)

### Comment [/api/v1.0/child/{child_id}/posts/{post_id}/comments/{comment_id}]

Resource representing a post comment.

+ Parameters
    + child_id: 5 - (number, required) - ID for the child
    + post_id: 2 - (number, required) - ID for the post
    + comment_id: 13 - (number, required) - ID for the comment

+ Attributes
    + id: 123 - (number, required) - ID for the comment
    + post_id: 45 - (number, required) - ID for the post
    + user_id: 33 - (number, required) - ID for the user
    + text: This is a message - (string, required) - message text
    + created_at: 20160215102334 - (string, required) - message created date

#### Retrieve comment [GET]

Retrieves an individual comment.

+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)
    + Attributes (Comment)

#### Update own comment [PUT]

Updates own comment.

+ Request (application/json)
    + Headers
    
            Authorization: Bearer {access_token}
    
    + Attributes (Comment)
    
+ Response 204 (application/json)

    Comment updated
    
    + Attributes (Comment)

#### Add new comment [POST]

Adds a new comment.

+ Request (application/json)
    + Headers
    
            Authorization: Bearer {access_token}
    
    + Attributes (Comment)

+ Response 201 (application/json)

    Comment created.
    
    + Attributes (Comment)

#### Delete my comment [DELETE]

+ Request
    + Headers
    
            Authorization: Bearer {access_token}
            
+ Response 204

### Post Likes [/api/v1.0/child/{child_id}/posts/{post_id}/likes]

Resource representing all likes for a post

+ Parameters
    + child_id: 15 - (number, required) - ID for the child
    + post_id: 4 - (number, required) - ID for the post

+ Attributes (array[Post Like])

#### List all likes for a post [GET]

Retrieves all likes for a post

+ Parameters
    + child_id: 41 - (number, required) - ID for the child
    + post_id: 111 - (number, required) - ID for the post

+ Request
    + Headers
    
            Authorization: Bearer {access_token}

+ Response 200 (application/json)

    + Attributes (Post Likes)

### Post Like [/api/v1.0/child/{child_id}/posts/{post_id}/likes/{like_id}]

Resource representing a post like.

+ Parameters
    + child_id: 6 - (number, required) - ID for the child
    + post_id: 55 - (number, required) - ID for the post
    + like_id: 22 - (number, required) - ID for the like

+ Attributes
    + id: 43 - (number, required) - ID for the like
    + post_id: 33 - (number, required) - ID for the post
    + user_id: 11 - (number, required) - ID for the user
    + created_at: 20151110083456 - (string, required) - like created datetime

#### Like a post [POST]

Likes a post.

+ Request (application/json)
    + Headers
    
            Authorization: Bearer {access_token}
    
    + Attributes (Post Like)

+ Response 201 (application/json)

    Comment created.
    
    + Attributes (Post Like)

#### Unlike a post [DELETE]

Unlikes a post.

+ Request
    + Headers
    
            Authorization: Bearer {access_token}
            
+ Response 204

### Comment Likes [/api/v1.0/child/{child_id}/posts/{post_id}/comments/{comment_id}/likes]

Resource representing all likes for a comment

+ Parameters
    + child_id: 55 - (number, required) - ID for the child
    + post_id: 114 - (number, required) - ID for the post
    + comment_id: 1 - (number, required) - ID for the post

+ Attributes (array[Comment Like])

#### List all likes for a comment [GET]

Retrieves all likes for a comment

+ Parameters
    + child_id: 41 - (number, required) - ID for the child
    + post_id: 111 - (number, required) - ID for the post
    + comment_id: 33 - (number, required) - ID for the comment

+ Request
    + Headers
    
            Authorization: Bearer {access_token}

+ Response 200 (application/json)

    + Attributes (Comment Likes)

### Comment Like [/api/v1.0/child/{child_id}/posts/{post_id}/comments/{comment_id}/likes/{like_id}]

Resource representing a comment like.

+ Parameters
    + child_id: 6 - (number, required) - ID for the child
    + post_id: 55 - (number, required) - ID for the post
    + comment_id: 87 - (number, required) - ID for the comment
    + like_id: 22 - (number, required) - ID for the like

+ Attributes
    + id: 43 - (number, required) - ID for the like
    + post_id: 33 - (number, required) - ID for the post
    + comment_id: 44 - (number, required) - ID for the comment
    + user_id: 11 - (number, required) - ID for the user
    + created_at: 20151110083456 - (string, required) - like created datetime

#### Like a comment [POST]

Likes a comment.

+ Request (application/json)
    + Headers
    
            Authorization: Bearer {access_token}
    
    + Attributes (Comment Like)

+ Response 201 (application/json)

    Comment like created.
    
    + Attributes (Comment Like)

#### Unlike a comment [DELETE]

Unlikes a comment.

+ Request
    + Headers
    
            Authorization: Bearer {access_token}
            
+ Response 204

### User [/api/v1.0/users/{user_id}]

Resource representing user

+ Parameters
    + user_id: 13 - (number, required) - The ID of the user

+ Attributes
    + id: 344 - (number, required) - The ID of the user
    + first_name - John - (string, required) - The first name for the user
    + last_name - Smith - (string, required) - The last name for the user
    + user_type - Staff - (enum, required) - The type of the user

### Users [/api/v1.0/users]

Resource representing all users

+ Attributes (array[User])

### Search Users [/api/v1.0/search/users/{user_name}]

Search users

+ Parameters

    + user_name: Anna' - (string, required) - The user name to search for.

+ Attributes (array[User])

#### List all user search results [GET]

List users

+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)
    
    + Attributes(Users)

### Search Posts [/api/v1.0/search/child_id/{child_id}/posts/{post_keyword}]

Search posts

+ Parameters

    + child_id: 1 - (number, required) - The ID for the child.
    + post_keyword: sick - (string, required) - The keyword for posts to search.

#### List all posts search results [GET]

+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)
    
    + Attributes (Posts)

### Search Reports [/api/v1.0/search/{child_id}/reports/{report_date}]

Search reports for specific date

+ Parameters
    + child_id: 11 - (number, required) - ID for the child
    + report_date: 20160202 - (string, required) - Date for specific report

#### Find date report [GET]

Find report for a specific date

+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)

    + Attributes (Report)

+ Response 404 (application/json)

        Not found

## General Settings [/api/v1.0/settings/{id}/general_settings]

+ Parameters

    + id: `1` (number) - The id of the user.

#### List general settings [GET]

+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)
    
    + Body
    
            {
                "language": "German",
                "push_notification": true
            }

## Language Settings [/api/v1.0/settings/{id}/language_setting]

+ Parameters

    + id: `1` (number) - The id of the user.

#### List language setting [GET]

+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)
    
    + Body
    
            {
                "language": "German"
            }

#### Modify language setting [PUT]
 Request
    + Headers

            Authorization: Bearer {access_token}
    
    + Attributes (language_setting)

+ Response 204

## Push Notification Settings [/api/v1.0/settings/{id}/push_notification_setting]

+ Parameters

    + id: `1` (number) - The id of the user.

#### List push notification setting [GET]

+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)
    
    + Body
    
            {
                "push_notifications": true
            }

#### Modify push notification setting [PUT]
Request
    + Headers

            Authorization: Bearer {access_token}
    
    + Attributes (push_notification_setting)

+ Response 204