FORMAT: 1A
HOST: http://giggles.ch

# Childcare API

Childcare application API calls.

## Sign In [/api/v1.0/sign_in/{email}{password}]

#### Sign in [POST]

Performs the login (Based on the documentation here: https://github.com/timdorr/model-s-api/blob/master/apiary.apib)

Returns an `access_token` which is passed along as a header with all future requests to authenticate the user.

You must provide the `Authorization: Bearer {access_token}` header in all other requests.

+ Parameters
    + email: 'test@test.com' (string) - User email
    + password: 'pass' (string) - User password
    

+ Response 200 (application/json)
    + Body

            {
              "access_token": "abc123",
              "token_type": "bearer",
              "expires_in": 7776000
            }

## Sign out [/api/v1.0/sign_out]

#### Sign out [DELETE]

+ Request
    + Headers

            Authorization: Bearer {access_token}


+ Response 204

## My Day [/api/v1.0/my_day/{id}]

+ Parameters

    + id: `1` (number) - The id of the Child.

### Report [/api/v1.0/reports/{child_id}/{?report_date}]

Resource representing one child report.

+ Parameters
    + child_id:  4 - (number, required) - child id for the report
    + report_date:  20160226 - (string, optional) - date for the report

+ Attributes
    + id: 1 (number, required) - ID of the report
    + child_id: 4 (number, required) - ID of the child
    + user_id: 3 (number, required) - ID of the staff
    + day: 20160226 (string, required) - Day of report
    + mood: Happy (string) - Child mood
    + food: {Morning => 1 Banana, Lunch => 2 portions} (object) - Daily food
    + sleep: 11.30-12.30, 14:00 - 14:30 (array) - Sleep times
    + nappy: 3 nappies, 2 poos (array) - Nappy changes
    + milestone:  I said my first word today: Mama (string) - Mileston text
    + notes: Some notes (string) - General notes

#### List child report [GET]

Display a child report for today or in specific date

+ Request
    + Headers
    
            Authorization: Bearer {access_token}

+ Response 200 (application/json)
    + Attributes (Report)
    
#### Create a new child report [POST]

Adds a new child report.

+ Request (application/json)
    + Headers
    
            Authorization: Bearer {access_token}
    + Attributes (Report)
            
+ Response 201 (application/json)
    
    Report created.
    
    + Attributes (Report)

## Posts [/api/v1.0/posts/{id}]

+ Parameters

    + id: `1` (number) - The id of the Child.

#### List all posts for child [GET]

+ Request
    + Headers

            Authorization: Bearer {access_token}


+ Response 200 (application/json)
    
    + Body

            [
                {
                    "id": "5",
                    "created_at": "2015-08-05T08:40:51.620Z",
                    "created_by": {
                        "id": "10",
                        "name": "Caretaker XYZ",
                        "image_url": "http://thecatapi.com/?id=e6u"
                    },
                    "text": "@Susanne is playing with @Anna",
                    "media": [
                        {
                            "media_type": "1",
                            "url" : "http://thecatapi.com/?id=dd4"
                        },
                        {
                            "media_type": "2",
                            "url": "http://thecatapi.com/?id=kd3"
                        }
                    ],
                    "likes": [
                        {
                            "id": "4",
                            "created_by": {
                                "id": "97",
                                "name": "Susanne's mom",
                                "image_url": "http://thecatapi.com/?id=e6u"
                            }
                        },
                        {
                            "id": "5",
                            "created_by": {
                                "id": "98",
                                "name": "Anna's mom",
                                "image_url": "http://thecatapi.com/?id=e6u"
                            }
                        },
                        {
                            "id": "6",
                            "created_by": {
                                "id": "99",
                                "name": "Some weird stalker",
                                "image_url": "http://thecatapi.com/?id=e6u"
                            }
                        }
                    ],
                    "comments": [
                        {
                            "id": "1",
                            "created_by": {
                                "id": "5",
                                "name": "Joe Doe",
                                "image_url": "http://thecatapi.com/?id=e6u"
                            },
                            "text": "First!"
                        }
                    ]
                }
            ]
            
### Post [/api/v1.0/child/{child_id}/posts/{post_id}]

Resource representing a post.

+ Parameters
    + child_id: 3 - (number, required) - ID for the child
    + post_id: 14 - (number, required) - ID for the post

+ Attributes
    + id: 34 - (number, required) - ID for the post
    + child_id: 5 - (number, required) - ID for the child
    + user_id: 33 - (number, required) - ID for the user
    + post_text: This is a post - (string, required) - Post text
    + media_url: http://test.com/resource/id - (string, optional) - URL for media
    + created_at: 20151023114534 - (string, required) - Datetime created

#### Retrieve post [GET]

Retrieves an individual post.

+ Request
    + Headers
    
            Authorization: Bearer {access_token}
            
+ Response 200 (application/json)
    + Attributes (Post)

#### Update own post [PUT]

Updates own post.

+ Request (application/json)
    + Headers
    
            Authorization: Bearer {access_token}
    
    + Attributes (Post)

+ Response 204 (application/json)

    Post updated
    
    + Attributes (Post)

#### Create a new post [POST]

Adds a new post.

+ Request (application/json)
    + Headers

            Authorization: Bearer {access_token}
            
    + Attributes (Post)
    
+ Response 201 (application/json)

    Post created.
    
    + Attributes (Post)

#### Delete my post [DELETE]

+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 204

### Comment [/api/v1.0/child/{child_id}/posts/{post_id}/comments/{comment_id}]

Resource representing a post comment.

+ Parameters
    + child_id: 5 - (number, required) - ID for the child
    + post_id: 2 - (number, required) - ID for the post
    + comment_id: 13 - (number, required) - ID for the comment

+ Attributes
    + id: 123 - (number, required) - ID for the comment
    + post_id: 45 - (number, required) - ID for the post
    + user_id: 33 - (number, required) - ID for the user
    + text: This is a message - (string, required) - message text
    + created_at: 20160215102334 - (string, required) - message created date

#### Retrieve comment [GET]

Retrieves an individual comment.

+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)
    + Attributes (Comment)

#### Update own comment [PUT]

Updates own comment.

+ Request (application/json)
    + Headers
    
            Authorization: Bearer {access_token}
    
    + Attributes (Comment)
    
+ Response 204 (application/json)

    Comment updated
    
    + Attributes (Comment)

#### Add new comment [POST]

Adds a new comment.

+ Request (application/json)
    + Headers
    
            Authorization: Bearer {access_token}
    
    + Attributes (Comment)

+ Response 201 (application/json)

    Comment created.
    
    + Attributes (Comment)

## Post Likes [/api/v1.0/posts/{post_id}/likes]
+ Parameters
    + post_id: `4` - (number) the post id

#### List post likes [GET /api/v1.0/posts/{post_id}/likes]

+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)
    + Body
    
            [
                "like": {
                            "id" : "1",
                            "name" : "John dad",
                            "created_at" : "2016-12-12"
                        },
                "like": {
                            "id": "2",
                            "name": "Sue mom",
                            "created_at" : "2016-12-13"
                        }
            ]

## Comment Likes [/api/v1.0/posts/{post_id}/comments/{comment_id}/likes]

+ Parameters
    + post_id: `4` - (number) the post id
    + comment_id: `1` - (number) the comment id

#### List comment likes [GET /api/v1.0/posts/{post_id}/comment/{comment_id}/likes]

+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)
    + Body
    
            [
                "like": {
                            "id" : "1",
                            "name" : "John dad",
                            "created_at" : "2016-12-12"
                        },
                "like": {
                            "id": "2",
                            "name": "Sue mom",
                            "created_at" : "2016-12-13"
                        }
            ]

## Search Users [/api/v1.0/search/users/{keyword}]

+ Parameters

    + keyword: `Anna`' (string) - The keyword for user to search.

#### List all user search results [GET]

+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)
    
    + Body

            [
                "user": {
                    "id": "10",
                    "name": "Caretaker XYZ",
                    "image_url": "http://thecatapi.com/?id=e6u"
                },
                
                "user": {
                    "id": "13",
                    "name": "Staff member",
                    "image_url": "http://images.com/?id=13d"
                }
            ]

## Search Posts [/api/v1.0/search/posts/{id}{keyword}]

+ Parameters

    + id: `1` (number) - The id of the children.
    + keyword: `sick`' (string) - The keyword for posts to search.

#### List all posts search results [GET]

+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)
    
    + Body

            [
                "post": {
                    "id": "10",
                    "message": "John was sick"
                },
                
                "post": {
                    "id": "13",
                    "name": "John was again sick"
                }
            ]

## General Settings [/api/v1.0/settings/{id}/general_settings]

+ Parameters

    + id: `1` (number) - The id of the user.

#### List general settings [GET]

+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)
    
    + Body
    
            {
                "language": "German",
                "push_notification": true
            }

## Language Settings [/api/v1.0/settings/{id}/language_setting]

+ Parameters

    + id: `1` (number) - The id of the user.

#### List language setting [GET]

+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)
    
    + Body
    
            {
                "language": "German"
            }

#### Modify language setting [PUT]
 Request
    + Headers

            Authorization: Bearer {access_token}
    
    + Attributes (language_setting)

+ Response 204

## Push Notification Settings [/api/v1.0/settings/{id}/push_notification_setting]

+ Parameters

    + id: `1` (number) - The id of the user.

#### List push notification setting [GET]

+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)
    
    + Body
    
            {
                "push_notifications": true
            }

#### Modify push notification setting [PUT]
Request
    + Headers

            Authorization: Bearer {access_token}
    
    + Attributes (push_notification_setting)

+ Response 204